  language: python
  python:
    - 3.4
    - 3.5
    - 3.6
    - 3.6-dev
    - nightly
  script:
    - python $PWD/DotStar -h
    - python $PWD/DotStar refresh listall
    - python $PWD/DotStar -y -r https://github.com/joachimschmidt557/DotStarTemplatePackage/raw/master/Test.star
    - python $PWD/DotStar -y $PWD/DotStar/Compile.star
