  language: python
  python:
    - 2.7
    - 3.5
    - 3.6
    - 3.6-dev
    - nightly
  script:
    - python $PWD/DotStar/DotStar.py -h
    - python $PWD/DotStar/DotStar.py -y -r https://github.com/joachimschmidt557/DotStarTemplatePackage/raw/master/Test.star
    - python $PWD/DotStar/DotStar.py -y $PWD/DotStar/Compile.star
