Compilation Information:
    Ignore files:
        - .git*
        - build*
        - __pycache__*
Author information:
  Name: joachimschmidt557
  Company: ''
  Website: https://github.com/joachimschmidt557
  Email: ''
Application Information:
  Name: dotstar
  Friendly Name: DotStar
  Description: Open file container format for universal, cross-platform applications
    and other files
  Version: 0.1.2
  Version System: SemVer
  Supported Platforms:
    - Win32
    - Win64
    #- macOS
    - Linux

Package Information:
  Name: dotstar
  Friendly Name: DotStar
  Description: Open file container format for universal, cross-platform applications
    and other files
  Version: 0.1.2
  Version System: SemVer
  Supported Platforms:
    - Win32
    - Win64
    #- macOS
    - Linux
#Dependencies:
#- Name: Python3
#  File: Python3.star
